// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlhhKKPecfK3LcWDX5FhLJWQAAAyktvw',
    appId: '1:116765061560:web:41912a83b47bfe696d5f4d',
    messagingSenderId: '116765061560',
    projectId: 'taskapp-2e3c7',
    authDomain: 'taskapp-2e3c7.firebaseapp.com',
    storageBucket: 'taskapp-2e3c7.firebasestorage.app',
    measurementId: 'G-RMPG6KXB57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9QwbKggQNKyS7WkxoUDrVHZ6NT76GZs',
    appId: '1:116765061560:android:e94e4710c58617096d5f4d',
    messagingSenderId: '116765061560',
    projectId: 'taskapp-2e3c7',
    storageBucket: 'taskapp-2e3c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UleVeePQ4fvmqmaSoN-Q0YOPGuBYAqc',
    appId: '1:116765061560:ios:1c00b36dc731b9376d5f4d',
    messagingSenderId: '116765061560',
    projectId: 'taskapp-2e3c7',
    storageBucket: 'taskapp-2e3c7.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UleVeePQ4fvmqmaSoN-Q0YOPGuBYAqc',
    appId: '1:116765061560:ios:1c00b36dc731b9376d5f4d',
    messagingSenderId: '116765061560',
    projectId: 'taskapp-2e3c7',
    storageBucket: 'taskapp-2e3c7.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQlhhKKPecfK3LcWDX5FhLJWQAAAyktvw',
    appId: '1:116765061560:web:f342d023b54c0bae6d5f4d',
    messagingSenderId: '116765061560',
    projectId: 'taskapp-2e3c7',
    authDomain: 'taskapp-2e3c7.firebaseapp.com',
    storageBucket: 'taskapp-2e3c7.firebasestorage.app',
    measurementId: 'G-3XMV5X9JQX',
  );
}
